### ISSUE TITLE
reproduce the experiment of the paper

### ISSUE THREAD

**Issue by Yanxing-Shi** [cheind/robot-pose#1]
Hello, I'm sorry to bother you, I want to reproduce the experiment of the paper,could you please share source code?

**Comment by cheind** [comment]
Hi @syx0629, thanks for your interest in our work! We are currently working on making in available for public usage. However, the work has been partly supported by companies and so we have to negotiate a bit.

I think however the info that we released should make it possibe for you to reproduce our results.
